# Macro file for the initialization
# in interactive session
#
# Set some default verbose
/control/verbose 1
/control/saveHistory
/run/verbose 0
/tracking/verbose 2


#
#
# Initialize kernel
#
# Visualization setting
/process/optical/processActivation Cerenkov false # non aggiunti in source (librerie etc)
/process/optical/processActivation Scintillation true

/control/execute 9MeVEF.mac


/run/initialize
/run/beamOn 0
/control/execute vis.mac




