# Macro file for the initialization
# in interactive session
#
# Set some default verbose
/control/verbose 1
/control/saveHistory
/run/verbose 0
/tracking/verbose 0


#
#
# Initialize kernel
#
# Visualization setting
/process/optical/processActivation Cerenkov false # non aggiunti in source (librerie etc)
/process/optical/processActivation Scintillation true

/run/initialize
/control/execute 9MeVEF.mac #Quello corrected è uguale 


/run/beamOn 10
/control/execute vis.mac




